FROM eclipse-temurin:21-jdk

# Set working directory
WORKDIR /app

# Copy your Maven project into the container
COPY . .

# Package the application
RUN ./mvnw clean install

# Run the Spring Boot app
CMD ["java", "-jar", "target/MISandInvoicingSystem-0.0.1-SNAPSHOT.jar"]
